### ISSUE TITLE
Enable user to select channel from available channel list

### ISSUE THREAD

**Issue by makmu** [makmu/outlook-matters#2]
It would be nice if the user could select the target channel from a list of available channels.

@maxlmo already did some [work](https://github.com/maxlmo/outlook-matters/commit/f8f7af5ed5c96eaf27671218b2ec4b0d04b7f23d) on this. However, I am not convinced that users will accept a user experience where they have to select a channel each time they log in. I think it would be better to extend the settings window to set up channel shortcuts. Those shortcuts could then appear as additional entries in the context submenu besides the "Settings..." entry. Some assistance when setting up shortcuts would be nice ;) (such as a complete list of available channels, fetched from mattermost).

**Comment by maxlmo** [comment]
I totaly agree with you. I am not satisfied with the usability of [[Add channel selection]](https://github.com/maxlmo/outlook-matters/commit/6c7c2d6fcac3d4f7c7c98a06056a71531d2bfc8b). It should only be used to test the functionality of  [[Fetch channel list from mattermost]](https://github.com/maxlmo/outlook-matters/commit/f3f193d9d4c5ddded386dbbfad0139b1e7a4abe3). 
However I have not yet managed it to create a dynamic submenu, besides the documentation of this special feature is pretty bad ;)

**Comment by maxlmo** [comment]
Short update. I am doing some progress on this issue
![channellist](https://cloud.githubusercontent.com/assets/17473929/14044661/59074308-f293-11e5-9e4e-31526b5588a7.jpg)

**Comment by makmu** [comment]
Thanks for your effort :)

IMHO we should reduce the menu depth to an absolute minimum. We could achieve this by a menu structure like this:
![menu](https://cloud.githubusercontent.com/assets/17351465/14062730/f11f8da0-f3a9-11e5-9d74-e8d9d9e15baa.png)

(BTW: ribbon xml to create this example menu:
```
<contextMenu idMso="ContextMenuMailItem">
      <menu id="MattermostContextMenu" imageMso="FillRight" label="Mattermost">
        <button id="channel1" imageMso="Forward" label="Off-Topic" onAction="OnPostClick" />
        <button id="channel2" imageMso="Forward" label="Plugin Test" onAction="OnPostClick" />
        <button id="channel3" imageMso="Forward" label="Town Square" onAction="OnPostClick" />
        <menuSeparator id="specialSectionSeparator" />
        <button id="ReplyButton" imageMso="Reply" label="As Reply..." onAction="OnReplyClick" />
        <menuSeparator id="settingsSectionSeparator" />
        <button id="SettingsButton" imageMso="ComAddInsDialog" label="Settings..." onAction="OnSettingsClick" />
      </menu>
</contextMenu>
```
)
