### ISSUE TITLE
Screenshots in readme.md / github start page

### ISSUE THREAD

**Issue by makmu** [makmu/outlook-matters#34]
I think it would be nice if we had one or two screenshots referenced in the global README.md so that when users find us on github they can immediately see what outlook-matters is all about and how it can be used.

**Comment by maxlmo** [comment]
Thats definetly a good idea :) Maybe we should try to keep it simple and cool. What content would you expect in these pictures? I just created 3 simple examples to discuss the text, definitely have to prettify the frames for the final version.
![outlook-matters_1](https://cloud.githubusercontent.com/assets/17473929/14234942/f9b3df7e-f9ef-11e5-9706-f11e4bc43418.png)
![outlook-matters_2](https://cloud.githubusercontent.com/assets/17473929/14234944/fe3a698c-f9ef-11e5-9b22-d7e10d997489.png)
![outlook-matters_3](https://cloud.githubusercontent.com/assets/17473929/14234946/00e2a050-f9f0-11e5-8e87-76792b5810eb.png)

Whats your opinion so far?
