### ISSUE TITLE
Invalidate session when settings are changed

### ISSUE THREAD

**Issue by makmu** [makmu/outlook-matters#5]
I just noticed that the session is not invalidated when settings are changed. In my particular case, I entered an invalid user name which led to an error when posting. So I corrected the user name and tried to post again. However, since the add-in still used the old session the settings change hat no effect and I still could not post. Only after restarting outlook the new settings were used to login to mattermost.
Note: When invalidating sessions we should make sure to log off the previous user properly (if possible).

**Comment by dkschlos** [comment]
I would like to fix this over the weekend. 
In addition to invalidating the session after changing the settings in Outlook, i think it would be desirable to evaluate all response status codes when interacting with Mattermost and trigger session invalidation if we get a 401 Unauthorized. This is the case after your login information has been changed inside Mattermost.

**Comment by makmu** [comment]
Thanks for fixing this :)
