### ISSUE TITLE
Error: Cannot deserialize the current JSON array

### ISSUE THREAD

**Issue by AndreasAWagner** [makmu/outlook-matters#67]
Correct settings made: URL, Team ID and e-mail.
After refresh channels, I'm asked for my password and the attached error message is thrown

![error](https://cloud.githubusercontent.com/assets/10194044/22415739/f6b5a77c-e6c9-11e6-84bb-0c5e51ef44d5.png)

using Outlook 2016 and Windows 10.

**Comment by kshankin** [comment]
+1 I get the same thing

**Comment by mohakem** [comment]
Getting the similar error on Outlook 2013

![image](https://cloud.githubusercontent.com/assets/4167068/24336772/899a6712-1262-11e7-92eb-f9981f2439bb.png)

**Comment by andi9310** [comment]
Same for me

**Comment by roetherb** [comment]
+1 on Outlook 2016 and Windows 7.

**Comment by nicetechguy** [comment]
+1 on Outlook 2016 and Windows 10

**Comment by rubiusus** [comment]
+1 same for me

**Comment by sumitag** [comment]
+1 same for me

**Comment by Master-Chief-5FDP** [comment]
+1 Outlook 2010, Windows 7 Pro , server Version: 3.10.0

**Comment by attzonko** [comment]
+1 Same here on MS Office Professional Plus 2013
